# Generated by Django 3.0.2 on 2020-02-25 04:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('code', models.CharField(max_length=21, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sub_icon', models.ImageField(default='sub_default.jpg', upload_to='sub_icons')),
                ('keywords', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
